import { Skill, ConnectorItem, PluginItem, MemoryConfig } from "./types";

export const DEFAULT_DIRECTORY_SKILLS: Skill[] = [
  {
    id: "skill-creator",
    name: "Skill Creator",
    slashCommand: "/skill-creator",
    description: "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to build custom agents.",
    icon: "Wand2",
    author: "Anthropic",
    downloads: "152K",
    category: "Anthropic",
    enabled: true,
    tags: ["Agentic", "Builder", "Meta"],
    systemPrompt: `You are equipped with the Skill Creator capability.
- Assist the user in designing clean, modular, and effective prompt skills for AI agents.
- Follow the SKILL.md specification: name, description, clear triggers, step-by-step instructions, and edge-case handling.
- Help test and refine system prompts and output formatting rules.`,
  },
  {
    id: "morning",
    name: "Morning Brief",
    slashCommand: "/morning",
    description: "Render the user's morning brief as a styled HTML artifact, or set it up as a recurring weekday task. Daily summary of tasks and news.",
    icon: "Sun",
    author: "Anthropic",
    downloads: "12.2K",
    category: "Anthropic",
    enabled: true,
    tags: ["Productivity", "Artifacts", "Daily"],
    systemPrompt: `You are equipped with the Morning Brief skill.
- Generate a comprehensive, beautiful daily morning briefing.
- Summarize top priorities, calendar highlights, key tech news, and system status in an elegant, structured format.
- Output rich visual styling or Markdown tables where appropriate.`,
  },
  {
    id: "import-memory",
    name: "Import Memory",
    slashCommand: "/import-memory",
    description: "Import a memory export from another AI assistant into memory — conversationally, additively, and with deduplication.",
    icon: "RotateCcw",
    author: "Anthropic",
    downloads: "3.9K",
    category: "Anthropic",
    enabled: true,
    tags: ["Memory", "Migration", "Context"],
    systemPrompt: `You are equipped with the Import Memory skill.
- Parse exported memories, user profiles, or custom instructions from ChatGPT, Claude, or other assistants.
- Categorize facts into user preferences, user profile, and topical knowledge without overwriting existing data.`,
  },
  {
    id: "canvas-design",
    name: "Canvas Design",
    slashCommand: "/canvas-design",
    description: "Create beautiful visual art in .png and .pdf documents using design philosophy. Layouts, typography, and visual hierarchies.",
    icon: "Palette",
    author: "Anthropic",
    downloads: "2M",
    category: "Anthropic",
    enabled: false,
    tags: ["Design", "Visuals", "Layout"],
    systemPrompt: `You possess the Canvas Design skill.
- Create aesthetic visual layouts, SVG diagrams, Tailwind CSS cards, and UI component mockups.
- Emphasize modern color harmony, white space, typography hierarchies, and subtle micro-interactions.`,
  },
  {
    id: "web-artifacts-builder",
    name: "Web Artifacts Builder",
    slashCommand: "/web-artifacts-builder",
    description: "Suite of tools for creating elaborate, multi-component HTML/React artifacts using modern frontend web standards.",
    icon: "Code2",
    author: "Anthropic",
    downloads: "1.3M",
    category: "Anthropic",
    enabled: true,
    tags: ["Artifacts", "HTML", "React"],
    systemPrompt: `You possess the Web Artifacts Builder skill.
- Build complete, standalone, interactive single-file HTML or React apps with inline CSS and modern JavaScript.
- Avoid broken external imports, use Lucide icons (inline SVG or CDN), and ensure responsive mobile/desktop layouts.`,
  },
  {
    id: "learn",
    name: "Deep Learner (Feynman)",
    slashCommand: "/learn",
    description: "Use this skill when the user wants intellectual understanding — learning how or why something works through analogies and first principles.",
    icon: "GraduationCap",
    author: "Anthropic",
    downloads: "1.1M",
    category: "Anthropic",
    enabled: false,
    tags: ["Learning", "Feynman", "Education"],
    systemPrompt: `You possess the Deep Learner skill based on the Feynman Technique.
- Break down any concept from first principles using intuitive real-world analogies.
- Avoid jargon or define it immediately.
- Test understanding with quick thought experiments or bite-sized questions.`,
  },
  {
    id: "mcp-builder",
    name: "MCP Server Builder",
    slashCommand: "/mcp-builder",
    description: "Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external tools and APIs.",
    icon: "Blocks",
    author: "Anthropic",
    downloads: "1M",
    category: "Anthropic",
    enabled: false,
    tags: ["MCP", "Tools", "Protocol"],
    systemPrompt: `You possess the MCP Server Builder skill.
- Guide the development of production-grade Model Context Protocol (MCP) servers in TypeScript and Python.
- Follow MCP specifications for resource templates, tool declarations, error handling, and JSON-RPC compliance.`,
  },
  {
    id: "theme-factory",
    name: "Theme Factory",
    slashCommand: "/theme-factory",
    description: "Toolkit for styling artifacts with a cohesive theme. Generates color palettes, typography rules, and CSS token maps.",
    icon: "Sparkles",
    author: "Anthropic",
    downloads: "1M",
    category: "Anthropic",
    enabled: false,
    tags: ["Theme", "Design", "CSS"],
    systemPrompt: `You possess the Theme Factory skill.
- Generate coordinated color schemes, dark/light contrast pairs, and CSS variables for web applications and documents.`,
  },
  {
    id: "brand-guidelines",
    name: "Brand Guidelines",
    slashCommand: "/brand-guidelines",
    description: "Applies official brand colors, typography, voice, and tone to any sort of artifact or copy.",
    icon: "Layers",
    author: "Anthropic",
    downloads: "897.8K",
    category: "Anthropic",
    enabled: false,
    tags: ["Branding", "Styleguide", "Marketing"],
    systemPrompt: `You possess the Brand Guidelines skill.
- Ensure all copy, documents, and designs strictly adhere to specified brand identity and tonal standards.`,
  },
  {
    id: "doc-coauthoring",
    name: "Doc Co-Authoring",
    slashCommand: "/doc-coauthoring",
    description: "Guide users through a structured workflow for co-authoring documentation, specs, RFCs, and architecture proposals.",
    icon: "FileText",
    author: "Anthropic",
    downloads: "887.1K",
    category: "Anthropic",
    enabled: false,
    tags: ["Docs", "Writing", "RFC"],
    systemPrompt: `You possess the Doc Co-Authoring skill.
- Work interactively with the user to outline, draft, and refine high-stakes technical documents, RFCs, and project proposals.`,
  },
  {
    id: "internal-comms",
    name: "Internal Communications",
    slashCommand: "/internal-comms",
    description: "Draft clear company announcements, engineering standup recaps, and incident post-mortems.",
    icon: "Megaphone",
    author: "Anthropic",
    downloads: "690K",
    category: "Anthropic",
    enabled: false,
    tags: ["Comms", "Standup", "Leadership"],
    systemPrompt: `You possess the Internal Comms skill.
- Draft crisp, empathetic, and unambiguous internal communications for engineering and cross-functional teams.`,
  },
  {
    id: "algorithmic-art",
    name: "Algorithmic & Generative Art",
    slashCommand: "/algorithmic-art",
    description: "Generate math-driven generative canvas art, particle simulations, fractals, and p5.js visualizations.",
    icon: "Binary",
    author: "Anthropic",
    downloads: "440K",
    category: "Anthropic",
    enabled: false,
    tags: ["Math", "Canvas", "Generative"],
    systemPrompt: `You possess the Algorithmic Art skill.
- Write creative coding scripts using HTML5 Canvas, WebGL, or SVG with mathematical formulas, noise, and generative algorithms.`,
  },
  // Community skills from alirezarezvani/claude-skills
  {
    id: "security-audit",
    name: "SOC & Security Auditor",
    slashCommand: "/security-audit",
    description: "Analyze system logs (Fortigate, Linux, Windows), detect OWASP vulnerabilities, audit IAM policies, and guide incident response.",
    icon: "ShieldAlert",
    author: "Alireza Rezvani (claude-skills)",
    downloads: "520K",
    category: "Community",
    enabled: true,
    tags: ["Cybersecurity", "SOC", "Logs", "OWASP"],
    sourceUrl: "https://github.com/alirezarezvani/claude-skills",
    systemPrompt: `You are an elite Cybersecurity & SOC Analyst.
- Analyze security logs (Fortigate, Snort, Zeek, Sysmon, auth.log, Windows Event logs) for indicators of compromise (IoCs).
- Provide threat severity levels, MITRE ATT&CK technique mappings, and actionable mitigation playbooks.
- Review code for OWASP Top 10 vulnerabilities, injection flaws, and authorization bypasses.`,
  },
  {
    id: "devops-engineer",
    name: "DevOps & Cloud Architect",
    slashCommand: "/devops-engineer",
    description: "Docker, Kubernetes manifests, Helm charts, GitHub Actions CI/CD pipelines, Terraform, and Linux administration.",
    icon: "Terminal",
    author: "Alireza Rezvani (claude-skills)",
    downloads: "480K",
    category: "Community",
    enabled: false,
    tags: ["DevOps", "Docker", "K8s", "CI/CD"],
    sourceUrl: "https://github.com/alirezarezvani/claude-skills",
    systemPrompt: `You are a Principal DevOps & Infrastructure Engineer.
- Write battle-tested Dockerfiles (multi-stage builds), Kubernetes manifests, and GitHub Actions workflows.
- Emphasize least privilege, minimal image size, health checks, and zero-downtime deployments.`,
  },
  {
    id: "code-reviewer",
    name: "Strict Code Reviewer",
    slashCommand: "/code-reviewer",
    description: "Rigorous pull request review for race conditions, memory leaks, performance bottlenecks, and idiomatic clean code.",
    icon: "CheckSquare",
    author: "Alireza Rezvani (claude-skills)",
    downloads: "610K",
    category: "Community",
    enabled: false,
    tags: ["Review", "CleanCode", "Performance"],
    sourceUrl: "https://github.com/alirezarezvani/claude-skills",
    systemPrompt: `You are a Strict Code Reviewer.
- Review code line-by-line for memory leaks, unhandled promises, race conditions, and typing weaknesses.
- Provide constructive feedback categorized as [CRITICAL], [WARNING], and [SUGGESTION].`,
  },
  {
    id: "sql-optimizer",
    name: "Database & SQL Optimizer",
    slashCommand: "/sql-optimizer",
    description: "PostgreSQL, MySQL, and SQLite query tuning, EXPLAIN ANALYZE interpretation, indexing strategy, and schema normalization.",
    icon: "Database",
    author: "Alireza Rezvani (claude-skills)",
    downloads: "350K",
    category: "Community",
    enabled: false,
    tags: ["SQL", "Postgres", "Database", "Indexing"],
    sourceUrl: "https://github.com/alirezarezvani/claude-skills",
    systemPrompt: `You are a Senior Database Administrator and SQL Optimization Specialist.
- Analyze query execution plans, recommend B-tree, GIN, or BRIN indexes, and rewrite queries to eliminate sequential scans.
- Optimize JOIN orders, CTEs, and window functions for high-throughput transactional and analytical workloads.`,
  },
];

export const DEFAULT_CONNECTORS: ConnectorItem[] = [
  // Popular
  {
    id: "gmail",
    name: "Gmail",
    description: "Connect your email inbox to draft emails, summarize threads, and organize unread messages.",
    category: "popular",
    icon: "Mail",
    badge: "Official",
    installed: true,
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Search, read, and analyze documents, spreadsheets, presentations, and team drive folders.",
    category: "popular",
    icon: "HardDrive",
    badge: "Official",
    installed: true,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Monitor team channels, search past conversations, and send notifications directly from chat.",
    category: "popular",
    icon: "MessageSquare",
    badge: "Official",
    installed: true,
    authType: "webhook",
    webhookUrl: "",
  },
  {
    id: "github",
    name: "GitHub",
    description: "Inspect repositories, read source code, analyze pull requests, and manage issues directly from chat.",
    category: "popular",
    icon: "GitBranch",
    badge: "Official",
    installed: true,
    authType: "apiKey",
    apiKey: "",
    repo: "",
  },
  {
    id: "discord",
    name: "Discord",
    description: "Dispatch messages, summaries, and agent task alerts directly to your Discord server channels.",
    category: "popular",
    icon: "MessageCircle",
    badge: "Community",
    installed: false,
    authType: "webhook",
    webhookUrl: "",
  },
  // Community
  {
    id: "blender-mcp",
    name: "Blender 3D (MCP)",
    description: "Connect live to your running Blender instance to procedurally generate 3D meshes, materials, lighting, and trigger renders via Python (bpy).",
    category: "popular",
    badge: "MCP 3D",
    installed: true,
    endpoint: "http://127.0.0.1:9876",
    authType: "none",
  },
  {
    id: "huxly",
    name: "Huxly",
    description: "Build, preview, and ship real mobile apps from chat — Expo, Flutter, and SwiftUI projects with a live preview.",
    category: "community",
    badge: "New",
    installed: false,
  },
  {
    id: "templated",
    name: "Templated.io",
    description: "Generate automated marketing images, banner videos, and PDFs from your design templates.",
    category: "community",
    badge: "New",
    installed: false,
  },
  {
    id: "mcp-nerve",
    name: "mcp.nerve.mattemena.com",
    description: "Manage Meta, TikTok, Google & Snapchat ads with AI-driven budget optimization and copy generation.",
    category: "community",
    badge: "New",
    installed: false,
  },
  {
    id: "hire-otto",
    name: "HireOtto - Google Analytics",
    description: "Google Analytics 4 (GA4) MCP for Claude with property discovery, custom reporting, and realtime user analytics.",
    category: "community",
    badge: "New",
    installed: false,
  },
  {
    id: "zentor",
    name: "Zentor",
    description: "Dynamic pricing and smart advertising for Mercado Libre, always protecting your margin and profitability.",
    category: "community",
    badge: "New",
    installed: false,
  },
  {
    id: "peerdom",
    name: "Peerdom",
    description: "Interactive organizational chart that lets AI query team responsibilities, roles, and accountability.",
    category: "community",
    badge: "New",
    installed: false,
  },
  {
    id: "nocodb",
    name: "NocoDB",
    description: "Connect to NocoDB to securely query, create, update, and manage your relational smart spreadsheet data.",
    category: "community",
    badge: "New",
    installed: false,
  },
  {
    id: "trueclicks",
    name: "TrueClicks MCP",
    description: "Audit, monitor, and analyze your Google Ads and PPC accounts for waste, errors, and missed opportunities.",
    category: "community",
    badge: "New",
    installed: false,
  },
  {
    id: "gadgetos",
    name: "GadgetOS",
    description: "Full-stack developer platform connecting backend cloud functions, serverless DB, and frontend hosting.",
    category: "community",
    badge: "New",
    installed: false,
  },
  {
    id: "joby-crm",
    name: "Joby CRM",
    description: "AI-native CRM to track client pipelines, follow-ups, contract signatures, and deal stages.",
    category: "community",
    badge: "New",
    installed: false,
  },
];

export const DEFAULT_PLUGINS: PluginItem[] = [
  {
    id: "productivity",
    name: "Productivity",
    description: "Manage tasks, plan your day, and build up memory of important context about your work. Syncs with your workflows.",
    author: "Anthropic",
    downloads: "2.5M",
    installed: true,
    category: "Anthropic",
    skillsIncluded: ["morning", "doc-coauthoring", "internal-comms"],
    systemPrompt: "You are enhanced with the Productivity Suite. Focus on actionable task planning, high-clarity summaries, and proactive time-management suggestions.",
  },
  {
    id: "design",
    name: "Design",
    description: "Accelerate design workflows — critique, design system management, UX writing, accessibility audits, research...",
    author: "Anthropic",
    downloads: "2.4M",
    installed: true,
    category: "Anthropic",
    skillsIncluded: ["canvas-design", "theme-factory", "brand-guidelines"],
    systemPrompt: "You are enhanced with the Design Suite. Provide world-class visual hierarchy, accessibility (WCAG) guidance, color harmony, and UX critique.",
  },
  {
    id: "marketing",
    name: "Marketing",
    description: "Create content, plan campaigns, and analyze performance across marketing channels. Maintain brand voice.",
    author: "Anthropic",
    downloads: "1.9M",
    installed: false,
    category: "Anthropic",
    skillsIncluded: ["brand-guidelines", "theme-factory"],
    systemPrompt: "You are enhanced with the Marketing Suite. Write compelling copy, structure omnichannel conversion funnels, and draft campaign blueprints.",
  },
  {
    id: "engineering",
    name: "Engineering",
    description: "Streamline engineering workflows — standups, code review, architecture decisions, incident response, and debugging.",
    author: "Anthropic",
    downloads: "1.7M",
    installed: true,
    category: "Anthropic",
    skillsIncluded: ["web-artifacts-builder", "mcp-builder", "code-reviewer", "devops-engineer"],
    systemPrompt: "You are enhanced with the Engineering Suite. Write robust, clean, and fully typed code. Address edge cases, error handling, and scalable architectures.",
  },
  {
    id: "data",
    name: "Data",
    description: "Write SQL, explore datasets, and generate insights faster. Build visualizations and dashboards, and turn raw data into decisions.",
    author: "Anthropic",
    downloads: "1.7M",
    installed: false,
    category: "Anthropic",
    skillsIncluded: ["sql-optimizer", "algorithmic-art"],
    systemPrompt: "You are enhanced with the Data Suite. Formulate optimal SQL queries, statistically evaluate metrics, and present data in structured Markdown tables.",
  },
  {
    id: "finance",
    name: "Finance",
    description: "Streamline finance and accounting workflows, from journal entries and reconciliation to financial statement analysis.",
    author: "Anthropic",
    downloads: "1.6M",
    installed: false,
    category: "Anthropic",
    skillsIncluded: ["sql-optimizer"],
    systemPrompt: "You are enhanced with the Finance Suite. Ensure financial accuracy, double-entry consistency, and analytical rigor in balance sheets and cash flows.",
  },
  {
    id: "product-management",
    name: "Product Management",
    description: "Write feature specs, plan roadmaps, and synthesize user research faster. Keep stakeholders updated and stay on schedule.",
    author: "Anthropic",
    downloads: "1.4M",
    installed: false,
    category: "Anthropic",
    skillsIncluded: ["doc-coauthoring", "internal-comms"],
    systemPrompt: "You are enhanced with the Product Management Suite. Write thorough PRDs, prioritize feature user stories (RICE/MoSCoW), and articulate user value.",
  },
  {
    id: "pdf-viewer",
    name: "PDF Viewer",
    description: "View, annotate, and extract insights from PDFs. Mark up contracts, fill forms with visual feedback, and extract key tables.",
    author: "Anthropic",
    downloads: "1.4M",
    installed: false,
    category: "Anthropic",
    skillsIncluded: ["doc-coauthoring"],
    systemPrompt: "You are enhanced with the PDF Analysis Suite. Deeply parse document layouts, extract tabular figures with high fidelity, and summarize lengthy whitepapers.",
  },
  {
    id: "sales",
    name: "Sales",
    description: "Prospect, craft outreach, and build deal strategy faster. Prep for calls, manage your pipeline, and write pitches.",
    author: "Anthropic",
    downloads: "1.3M",
    installed: false,
    category: "Anthropic",
    skillsIncluded: ["brand-guidelines"],
  },
  {
    id: "operations",
    name: "Operations",
    description: "Optimize business operations — vendor management, process documentation, change management, capacity planning.",
    author: "Anthropic",
    downloads: "1.3M",
    installed: false,
    category: "Anthropic",
    skillsIncluded: ["doc-coauthoring", "internal-comms"],
  },
  {
    id: "legal",
    name: "Legal",
    description: "Review contracts, spot liability redlines, analyze compliance policies, and draft terms of service.",
    author: "Anthropic",
    downloads: "1.1M",
    installed: false,
    category: "Anthropic",
    skillsIncluded: ["doc-coauthoring"],
  },
  {
    id: "enterprise-search",
    name: "Enterprise Search",
    description: "Search across company wikis, Jira tickets, Notion pages, and team conversations with unified semantic indexing.",
    author: "Anthropic",
    downloads: "980K",
    installed: false,
    category: "Anthropic",
    skillsIncluded: ["import-memory"],
  },
];

export const DEFAULT_MEMORY_CONFIG: MemoryConfig = {
  generateFromChats: true,
  includeSensitive: false,
  items: [
    {
      id: "pref_response",
      category: "preference",
      title: "Preferences",
      content: "How the user wants the AI to respond — direct, technical, modern code with no fluff or unnecessary preamble.",
      updatedAt: Date.now() - 86400000 * 5,
      enabled: true,
    },
    {
      id: "prof_user",
      category: "profile",
      title: "Profile",
      content: "Who the user is — Cybersecurity Analyst & Full-Stack Developer specializing in log monitoring and agentic systems.",
      updatedAt: Date.now() - 86400000 * 5,
      enabled: true,
    },
    {
      id: "topic_gaming",
      category: "topic",
      title: "Gaming",
      content: "Gaming interests — tactical simulations, strategy games, and game architecture analysis.",
      updatedAt: Date.now() - 86400000 * 5,
      enabled: true,
    },
    {
      id: "topic_work",
      category: "topic",
      title: "Recent Work",
      content: "Recent SOC analyst work activity, Fortigate firewall log analysis, detection rules, and automated Ollama workflows.",
      updatedAt: Date.now() - 86400000 * 5,
      enabled: true,
    },
    {
      id: "topic_tools",
      category: "topic",
      title: "Tools",
      content: "Security tools and platforms the user works with — Splunk, Wireshark, Docker, Linux (Ubuntu/Debian), Next.js, and Ollama.",
      updatedAt: Date.now() - 86400000 * 5,
      enabled: true,
    },
  ],
};
